project:
  type: website
  output-dir: docs

website:
  title: "Seng Yee Sin"
  description: "PhD student in Political Science at Florida State University studying historical political economy, political violence, and Southeast Asia."
  navbar:
    pinned: false
    title: "Seng Yee Sin"
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: /file/cv.pdf
  page-footer:
    border: false
    left: "© 2026 Seng Yee Sin"
    right:
      - icon: envelope
        href: mailto:ss25bq@fsu.edu
        aria-label: Email
      - icon: person-vcard
        href: https://orcid.org/0009-0004-5400-4688
        aria-label: ORCID
  open-graph: true

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    section-divs: false
    anchor-sections: false
    smooth-scroll: true
    link-external-newwindow: true
    grid:
      body-width: 900px
      sidebar-width: 0px
      margin-width: 0px
